### ISSUE TITLE
Cannot Import "Radios" or "Checkboxes"

### ISSUE THREAD

**Issue by shaquillaevelyn** [surevine/govuk-react-jsx#108]
Please review the Radios and Checkbox functionality. Unable to use in UI. Possible that other elements are unusable.

 Try `npm i --save-dev @types/govuk-react-jsx` if it exists or add a new declaration (.d.ts) file containing `declare module 'govuk-react-jsx';`  TS7016

     9 |   Paragraph,
    10 | } from 'govuk-react';
  > 11 | import { Radios } from 'govuk-react-jsx';
       |                        ^

**Comment by andymantell** [comment]
Hi,
Please can your post a git repository containing a minimal reproduction of this issue. The components are demonstrably working under create react app and nextjs currently. I suspect something is awry with your setup but I need to see the context that it's running in. Thanks.

**Comment by andymantell** [comment]
Also, your example contains references to govuk-react which is a different module entirely. This module is govuk-react-jsx.

**Comment by andymantell** [comment]
Closing this as I don't think there's an issue here. Please feel free to reopen with an example of an error if you can.
