### ISSUE TITLE
I guess this library doesn't work with gatsby react?

### ISSUE THREAD

**Issue by UPLukeet** [surevine/govuk-react-jsx#119]
When I try and import an element in gatsby react I get a multitude of issues and errors, has it been tested on gatsby before or is this an issue with my local build?

**Comment by UPLukeet** [comment]
ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/components/accordion/accordion' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/accordion'

If you're trying to use a package make sure that 'govuk-frontend/govuk/components/accordion/accordion' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/govuk/components/accordion/index.js:42:21


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/components/button/button' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/button'

If you're trying to use a package make sure that 'govuk-frontend/govuk/components/button/button' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/govuk/components/button/index.js:69:21


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/components/character-count/character-count' in
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/character-count'

If you're trying to use a package make sure that 'govuk-frontend/govuk/components/character-count/character-count' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/govuk/components/character-count/index.js:49:21


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/components/error-summary/error-summary' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/error-summary'

If you're trying to use a package make sure that 'govuk-frontend/govuk/components/error-summary/error-summary' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/govuk/components/error-summary/index.js:45:21


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/assets/images/govuk-logotype-crown.png' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/header'

If you're trying to use a package make sure that 'govuk-frontend/govuk/assets/images/govuk-logotype-crown.png' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/govuk/components/header/index.js:22:49


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/components/header/header' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/header'

If you're trying to use a package make sure that 'govuk-frontend/govuk/components/header/header' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/govuk/components/header/index.js:58:21


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/components/notification-banner/notification-banner' in
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/notification-banner'

If you're trying to use a package make sure that 'govuk-frontend/govuk/components/notification-banner/notification-banner' is installed. If you're trying to use a local file make sure that the path is
correct.

File: node_modules/govuk-react-jsx/govuk/components/notification-banner/index.js:47:21


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/components/tabs/tabs' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/tabs'

If you're trying to use a package make sure that 'govuk-frontend/govuk/components/tabs/tabs' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/govuk/components/tabs/index.js:44:21


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/assets/images/favicon.ico' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'

If you're trying to use a package make sure that 'govuk-frontend/govuk/assets/images/favicon.ico' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/govuk/template/index.js:16:38


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/assets/images/govuk-mask-icon.svg' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'

If you're trying to use a package make sure that 'govuk-frontend/govuk/assets/images/govuk-mask-icon.svg' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/govuk/template/index.js:18:44


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/assets/images/govuk-apple-touch-icon-180x180.png' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'

If you're trying to use a package make sure that 'govuk-frontend/govuk/assets/images/govuk-apple-touch-icon-180x180.png' is installed. If you're trying to use a local file make sure that the path is
correct.

File: node_modules/govuk-react-jsx/govuk/template/index.js:20:54


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/assets/images/govuk-apple-touch-icon-167x167.png' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'

If you're trying to use a package make sure that 'govuk-frontend/govuk/assets/images/govuk-apple-touch-icon-167x167.png' is installed. If you're trying to use a local file make sure that the path is
correct.

File: node_modules/govuk-react-jsx/govuk/template/index.js:22:54


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/assets/images/govuk-apple-touch-icon-152x152.png' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'

If you're trying to use a package make sure that 'govuk-frontend/govuk/assets/images/govuk-apple-touch-icon-152x152.png' is installed. If you're trying to use a local file make sure that the path is
correct.

File: node_modules/govuk-react-jsx/govuk/template/index.js:24:54


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/assets/images/govuk-apple-touch-icon.png' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'

If you're trying to use a package make sure that 'govuk-frontend/govuk/assets/images/govuk-apple-touch-icon.png' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/govuk/template/index.js:26:50


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/assets/images/govuk-opengraph-image.png' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'

If you're trying to use a package make sure that 'govuk-frontend/govuk/assets/images/govuk-opengraph-image.png' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/govuk/template/index.js:28:50


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/components/radios/radios' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/utils'

If you're trying to use a package make sure that 'govuk-frontend/govuk/components/radios/radios' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/utils/Boolean.js:75:21


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'govuk-frontend/govuk/components/checkboxes/checkboxes' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/utils'

If you're trying to use a package make sure that 'govuk-frontend/govuk/components/checkboxes/checkboxes' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/utils/Boolean.js:98:21


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'react-router-dom' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/utils'

If you're trying to use a package make sure that 'react-router-dom' is installed. If you're trying to use a local file make sure that the path is correct.

File: node_modules/govuk-react-jsx/utils/Link.js:16:22

failed Re-building development bundle - 2.134s
ERROR in ./node_modules/govuk-react-jsx/govuk/components/accordion/index.js 42:21-48:68
Module not found: Error: Can't resolve 'govuk-frontend/govuk/components/accordion/accordion' in 
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/accordion'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 7:17-50
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/components/button/index.js 69:21-75:62
Module not found: Error: Can't resolve 'govuk-frontend/govuk/components/button/button' in 
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/button'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 46:14-44
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/components/character-count/index.js 49:21-55:80
Module not found: Error: Can't resolve 'govuk-frontend/govuk/components/character-count/character-count' in 
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/character-count'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 59:22-61
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/components/error-summary/index.js 45:21-51:76
Module not found: Error: Can't resolve 'govuk-frontend/govuk/components/error-summary/error-summary' in 
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/error-summary'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 137:20-57
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/components/header/index.js 22:49-119
Module not found: Error: Can't resolve 'govuk-frontend/govuk/assets/images/govuk-logotype-crown.png' in 
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/header'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 189:14-44
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/components/header/index.js 58:21-64:62
Module not found: Error: Can't resolve 'govuk-frontend/govuk/components/header/header' in 
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/header'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 189:14-44
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/components/notification-banner/index.js 47:21-53:88
Module not found: Error: Can't resolve 'govuk-frontend/govuk/components/notification-banner/notification-banner' in 
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/notification-banner'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 254:26-69
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/components/tabs/index.js 44:21-50:58
Module not found: Error: Can't resolve 'govuk-frontend/govuk/components/tabs/tabs' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/components/tabs'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 358:12-40
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/template/index.js 16:38-95
Module not found: Error: Can't resolve 'govuk-frontend/govuk/assets/images/favicon.ico' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 410:16-37
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/template/index.js 18:44-109
Module not found: Error: Can't resolve 'govuk-frontend/govuk/assets/images/govuk-mask-icon.svg' in 
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 410:16-37
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/template/index.js 20:54-134
Module not found: Error: Can't resolve 'govuk-frontend/govuk/assets/images/govuk-apple-touch-icon-180x180.png' in 
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 410:16-37
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/template/index.js 22:54-134
Module not found: Error: Can't resolve 'govuk-frontend/govuk/assets/images/govuk-apple-touch-icon-167x167.png' in 
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 410:16-37
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/template/index.js 24:54-134
Module not found: Error: Can't resolve 'govuk-frontend/govuk/assets/images/govuk-apple-touch-icon-152x152.png' in 
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 410:16-37
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/template/index.js 26:50-122
Module not found: Error: Can't resolve 'govuk-frontend/govuk/assets/images/govuk-apple-touch-icon.png' in 
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 410:16-37
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/govuk/template/index.js 28:50-121
Module not found: Error: Can't resolve 'govuk-frontend/govuk/assets/images/govuk-opengraph-image.png' in 
'/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/govuk/template'
 @ ./node_modules/govuk-react-jsx/govuk/index.js 410:16-37
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/utils/Boolean.js 75:21-81:62
Module not found: Error: Can't resolve 'govuk-frontend/govuk/components/radios/radios' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/utils'
 @ ./node_modules/govuk-react-jsx/govuk/components/checkboxes/index.js 14:15-48
 @ ./node_modules/govuk-react-jsx/govuk/index.js 72:18-52
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/utils/Boolean.js 98:21-104:70
Module not found: Error: Can't resolve 'govuk-frontend/govuk/components/checkboxes/checkboxes' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/utils'
 @ ./node_modules/govuk-react-jsx/govuk/components/checkboxes/index.js 14:15-48
 @ ./node_modules/govuk-react-jsx/govuk/index.js 72:18-52
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

ERROR in ./node_modules/govuk-react-jsx/utils/Link.js 16:22-49
Module not found: Error: Can't resolve 'react-router-dom' in '/Users/lukeellulturner/Documents/Work/canterbury-council-frontend/node_modules/govuk-react-jsx/utils'
 @ ./node_modules/govuk-react-jsx/govuk/components/back-link/index.js 16:12-42
 @ ./node_modules/govuk-react-jsx/govuk/index.js 20:16-49
 @ ./src/canerbury-gov-components/canterburyToast.jsx 10:0-47 40:24-36
 @ ./src/components/cookie-settings.js 15:0-78 228:64-79
 @ ./src/components/blocks-render.js 33:0-63 435:54-68
 @ ./src/templates/inner-page.js 9:0-55 129:56-68
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 61:11-63:5
 @ ./.cache/app.js 16:0-52 29:87-33:1 32:29-42 35:27-40 29:0-33:2

**Comment by UPLukeet** [comment]
For references all I have tried to import so far is a cookie banner and I get all these errors

**Comment by UPLukeet** [comment]
`import { CookieBanner } from "govuk-react-jsx"`
Importing like so

**Comment by UPLukeet** [comment]
sorry my mistake didn't read install instructions clearly

**Comment by andymantell** [comment]
No problem. I take it you got it working in the end?
