### ISSUE TITLE
Inline radio with conditionals renders strangely

### ISSUE THREAD

**Issue by domhall** [surevine/govuk-react-jsx#143]
<img width="916" alt="image" src="https://user-images.githubusercontent.com/67909035/157487839-2e43287c-6d8a-4240-9ab5-a974a6b741a9.png">
See the storybook entry: https://govuk-react-jsx.netlify.app/?path=/story/radios--inline-with-conditional-items

Not sure why you would ever want this feature but it is broken on the storybook. It ceases being inline when you select an option also the grey bar for the inline form entry overlaps with radio items. Might be resolved by just removing this case from storybook and discouraging it

**Comment by andymantell** [comment]
Thanks @domhall , good spot! I can see they've been doing some stuff in this area, in this commit:

https://github.com/alphagov/govuk-frontend/commit/d5249619303498a8afca666658318094cdc0eea1

I'll investigate and see what I need to do. I'm slightly puzzled what's happened but either way - they have removed the demo so I will follow suit (Basically I just need to upgrade to govuk-frontend@4.0.1 and this should go away magically)

**Comment by domhall** [comment]
Ah looking like they made it intentionally ugly to discourage breaking the standard. Removing the demo seems like a good shout :)
