### ISSUE TITLE
Include differences between this project and govuk-react/govuk-react in the README

### ISSUE THREAD

**Issue by brightpixels** [surevine/govuk-react-jsx#36]
Hello,
Is it possible to include pros and cons of this repo, compared to https://github.com/govuk-react/govuk-react. In the motivation section, maybe say why you started this repo instead of contributing to govuk-react repo as the aim is the same.

Both look to me can do the job (i.e. react-based GDS components). Downside for me with https://github.com/govuk-react/govuk-react is that not much activity is going on but the weekly downloads are higher (update: just realised this repo is only 2 months old so downloads aren't useful metric). On the other hand, this repo appears to be using the latest GDS stylesheets.

Thanks

**Comment by andymantell** [comment]
Hi @brightpixels ,

Fair point - I will have a go at clarifying this.  For your purposes immediately, the main differences are as follows:

govuk-react does not consume the govuk-frontend code - it is an _implementation_ of the govuk-design-system - i.e. it looks like the design system, but it is not using any of the original GDS code. CSS has been rebuilt from the ground up, JavaScript behaviours have been rebuilt, and markup patterns are different.

gouk-react-jsx _does_ consume the govuk-frontend code. The CSS and JS behaviours are directly pulled from the GDS code and markup patterns are kept in step using a comprehensive test suite to ensure it is the same as the reference Nunjucks implementation in the govuk-frontend repository.

In my opinion, the advantages of my approach vs that of govuk-react are:

- Easier to stay up to date with upstream improvements from govuk-frontend 
- Markup patterns that GDS have carefully crafted to meet accessibility requirements are preserved (Including Aria attributes, which are currently missing from govuk-react-jsx)
- Simpler and less engineering in general - there is just _less code_ to maintain here. Less moving parts.

There are doubtless some advantages to govuk-react - it's certainly more comprehensive. For example govuk-react implements components for the grid system, heading levels etc etc. This repository does not do this - instead you simple use plain html. So where govuk-react would have you write `<GridCol>`, in this repository you would write `<div className="grid-col">`

Does that answer your question if I were to drop something like this into the readme?

**Comment by brightpixels** [comment]
This is exactly what's needed in the README. Thank you. But could you also mention any potential downsides you could foresee just to be objectives. What use cases you don't recommend and recommended setup etc. 

When you say directly pulled from GDS, are you saying this project will always be in sync with GDS and doesn't depend on the maintainers efforts to stay up to date?

I am happy to raise PR to update your README.

**Comment by andymantell** [comment]
The CSS and JS are pulled directly from govuk-frontend and require "no effort" to keep up to date apart from updating the govuk-frontend version number in package.json. The effort lies in porting any changes to the govuk-frontend Nunjucks templates across to JSX / React. Most of the time this is pretty minimal.

The downsides of this vs govuk-react are mostly "developer experience" I guess - as alluded to above, you have to write more raw html than you would with govuk-react because I haven't provided grid components, heading components etc etc. But whether that's truly a downside is a matter of opinion - personally I don't mind using the raw html. But I guess you could argue that if I were using an abstracted <GridCol> component, that upstream changes from govuk-frontend could be brought into my app more easily. If govuk changed all the grid classes and I'm just using raw html, I'd have more things to change on my application.

I can't think of any more downsides for the moment.

**Comment by andymantell** [comment]
In terms of recommended setup, there's a codesandbox with the basics running inside create-react-app:

https://codesandbox.io/s/govuk-react-jsx-cra-jeiku

**Comment by brightpixels** [comment]
The other question is around the point in the README: "strike a balance between mirroring the GOV.UK Nunjucks params vs ideomatic React props"

As a consumer of this repo, how do I know when to use GDS classnames because there is no React component available (e.g. grid-col) and when I can use a React component (e.g. <Panel>). Is it a matter of looking at Storybook?

Also, to be clear, why haven't you provided components for things like heading etc? Is it time issue (and you are open to contribution) or your viewpoint is that using raw HTML is better for various reasons? If the latter, would be nice to explain this opinion as well in the README.


From everything you said so far, I am more inclined to use this repo, purely because you are in sync with GDS but I will probably end up creating components to avoid writing the same chunk of HTML. And like you said, if a changed happened somewhere in the raw HTML, it can be done in one place.

**Comment by andymantell** [comment]
Yeah I think it's a case of reading the storybook - everything that's available is in there. But maybe there could be a sentence in the readme along these lines:

"This repository includes components for all the govuk-frontend components, but does not include components for smaller base styles like headings, paragraphs, links etc"

As for _why_, that is a good question. I think initially it was a case of doing the smallest amount of code required to get a decent implementation of the govuk-frontend components. I don't think I'm philosophically against having them in here. It just didn't seem very necessary at the time, but I do see the argument for including them.

I guess we are mostly just talking about typography and grid aren't we. Can you think of anything else? If you want to add these I'm happy to accept contributions. It would certainly make things like typing `<p class="govuk-body">` all the time much less tedious.

**Comment by brightpixels** [comment]
Thank you the quick replies. Very useful.

The fact that you cover all components listed here https://design-system.service.gov.uk/components/ as React components, is really good. Only feedback is to keep naming consistent with GDS (e.g. text input vs input).

I would make this sentence as early as possible in the README:

````
This repository includes [components](https://surevine.github.io/govuk-react-jsx/) for all the [govuk-frontend components](https://design-system.service.gov.uk/components/). 

There are no components provided currently for [Styles](https://design-system.service.gov.uk/styles/) and [patterns](https://design-system.service.gov.uk/patterns/) but can be achieved by using the appropriate `classes`.
````

"I guess we are mostly just talking about typography and grid aren't we. Can you think of anything else?" All my questions are based what I read on the README. I haven't actually used it. I was just in process of understanding this repo before I commit my time, specially on how it differs from the other repos. I will create an issue or PR if I feel

**Comment by andymantell** [comment]
Technically that is GDS being inconsistent with themselves! In their GitHub repository, text input is known as input. See https://github.com/alphagov/govuk-frontend/tree/master/src/govuk/components/input

I'll collate all the above feedback and drop it into the readme the next time I get a moment. Thanks very much for your thoughts.

I'll open a separate ticket for creating grid and typography components...

**Comment by andymantell** [comment]
@brightpixels Could you have a look at #38 when you get a chance and let me know if you think it successfully clarifies the questions you originally had? Thanks!

**Comment by brightpixels** [comment]
Love it. Thank you.
