### ISSUE TITLE
Error module parse failed: Unexpected charcter

### ISSUE THREAD

**Issue by brightpixels** [surevine/govuk-react-jsx#58]
Hello,
Firstly, I don't think this is a problem with this lib but if you can help, I would be grateful.

I am working on a React project that has been setup up manually (i.e. without the use of create-react-app), and when I try to import a component from this library like Input or Button, I am getting this error: 
````
Uncaught error: Module parse failed: Unexpected character '  ' (1:0)
You may need an appropriate loader to handle this file type.
(Soure code omitted for this binary file)
    at Object.<anonymous> (HamletUtils.js:536)
    at __webpack_require__(bootstrap_ff7b80..:678)
    .....
````
The webpack config has the following loaders:
- babel-loader
- url-loader
- style-loader
- eslint-loader

I got no idea where to start with this error has it feel little generic. Any hints would be appreciated.

**Comment by andymantell** [comment]
Curious. Would you be able to put together a minimal example repo with your webpack setup and a simple "hello world" app demonstrating the failure?

**Comment by brightpixels** [comment]
Give me an hour please.

**Comment by brightpixels** [comment]
Took well over an hour, it was painstaking. Webpack and babel configs are like-for-like, taking into account version numbers.

When I try to import Input I am getting similar error (not exact) about a loader. This error disappears if I remove the Input component import from my index.js.

https://github.com/brightpixels/error-reproduction

Btw, something separate, I was prompted by terminal about a 'not found module: react-markdown' initially, should this be a dependancy that must be installed with this lib.

**Comment by andymantell** [comment]
Your repo seems to be using `govuk-react`, not this library which is `govuk-react-jsx`.

I'll have a quick look tomorrow and see if I can spot the issue for you anyway, but if you are using govuk-react the issue might be better raised over there.

**Comment by brightpixels** [comment]
Sorry, long day. I have pushed again with the correct import now (igovuk-react-jsx). The error now is along the same lines 
```
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
````

But this time it's more specific about which file: `ERROR in ./node_modules/govuk-frontend/govuk/assets/images/favicon.ico`

Whereas in the real project I am working on it doesn't for some reason tell me which file is causing the error

**Comment by brightpixels** [comment]
Error disappeared as soon as I added 'ico' to the url-loader 

Thanks for your help :)

**Comment by andymantell** [comment]
Ah excellent. That was going to be my suggestion but you've got there before me.

I would highly suspect the issue will be similar under govuk-react as well. Not sure which file type, but it'll be the same problem most likely.
