### ISSUE TITLE
Looking for example of usage of Input with react-text-mask

### ISSUE THREAD

**Issue by brightpixels** [surevine/govuk-react-jsx#96]
Hello,
I am looking for an example of govuk-react-jsx input component used with react-text-mask component please. Use case examples is guide use to fill in a credit card number or phone number

**Comment by andymantell** [comment]
The docs suggest passing a render prop allowing you to specify a custom component:

https://www.npmjs.com/package/react-text-mask#customize-rendered-input-component

Have you tried this yet?

**Comment by brightpixels** [comment]
I have read this earlier and didn’t think of it as relevant to what I was looking for. Will have a go and report back.

**Comment by andymantell** [comment]
Closing this for now. Feel free to reopen if there is an issue within govuk-react-jsx
