### ISSUE TITLE
Button issue with Formik

### ISSUE THREAD

**Issue by oddjones** [surevine/govuk-react-jsx#99]
Hi there - I've noticed in the Formik example (and in a different Formik example I've been asked to review) that there's a recurrent `Cannot read property 'addEventListener' of null at e.init (button.js:718)` error being pumped into the console - I've been having the devil's own job chasing it down - has anybody there figured out what's causing it?

**Comment by andymantell** [comment]
ah, when you press the submit button?

**Comment by oddjones** [comment]
yep - although I'm making things hard for myself by trying to implement it in NextJS and I'm having it happen when I interact with any field on the form

**Comment by andymantell** [comment]
I can reproduce the issue in the Formik and React-hook-form examples here:

https://surevine.github.io/govuk-react-jsx-examples/

I'm in the middle of something for a second, but I'll try and take a look at the end of today.

Does the button "work" apart from this? Or are you totally blocked from doing what you're doing?

**Comment by oddjones** [comment]
Ah mate - seriously - it's just bugging me ;-) The button does seem to work - but because my example uses NextJS it's way more shouty about the error (no console there - right up in your face) - it can wait - no rush at all

**Comment by andymantell** [comment]
ok that's good, so long as you can do what you need to do for the moment.

Thanks for raising it - I'll sort it out as soon as I can.

**Comment by andymantell** [comment]
I think this might be the answer:

https://stackoverflow.com/a/63033314

**Comment by oddjones** [comment]
With the UseEffect being inside Formik? (guesses)
http://about.me/dominic.jones

**Comment by andymantell** [comment]
sorry that was sort of a note to myself. It's the way that I'm initialising the govuk-frontend button javascript inside my component. It's not something you can fix at your end...

**Comment by oddjones** [comment]
>>smiles<<

**Comment by andymantell** [comment]
@oddjones and @SamChatfield - I think I have a simple fix for this. So simple I am suspicious of it, but I'm hoping it's a goer.

I'm gonna pursue it this weekend and extend my pipeline to publish release candidates so that you can both test it out before I let it out into the wild...

**Comment by oddjones** [comment]
Nice - I'll keep an eye open
http://about.me/dominic.jones

**Comment by andymantell** [comment]
@oddjones I've published as a release candidate so you can give it a whirl. If you wouldn't mind doing `npm install govuk-react-jsx@next` and seeing how that goes that would be great. Thanks!

**Comment by andymantell** [comment]
@oddjones This has been released now as https://github.com/surevine/govuk-react-jsx/releases/tag/v5.1.0

Please let me know if you have any further issues.
